name: dbpedia2
dependencies:
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- requests=2.9.1=py27_0
- setuptools=20.7.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - html5lib==0.9999999
  - isodate==0.5.4
  - keepalive==0.5
  - mwclient==0.8.1
  - pyparsing==2.1.3
  - rdflib==4.2.1
  - six==1.10.0
  - sparqlwrapper==1.7.6

